### ISSUE TITLE
Where are the locale files?

### ISSUE THREAD

**Issue by tsenying** [SlexAxton/messageformat.js#119]
They used to be in the locales directory?
In particular, looking for the Latvian version.

**Comment by SlexAxton** [comment]
Instead of hard-coding these files into the library we now use the `make-plural` library to pull them directly out of the most recent CLDR data.

If you don't feel like going through CLDR data, you can just look through our history, assuming the rules haven't been updated. Here they are at version 2.0 release: https://github.com/SlexAxton/messageformat.js/tree/409b510e805527fe85bc4f05b92e1c546953bde8/locale

**Comment by tsenying** [comment]
Thanks @SlexAxton
Appreciate the quick reply.
