### ISSUE TITLE
MIssing Local directory

### ISSUE THREAD

**Issue by bleuscyther** [SlexAxton/messageformat.js#120]
In the latest version, there is no local directory anymore.

**Comment by SlexAxton** [comment]
We use the make-plural dependency to pull locale data directly from CLDR data. You can either use that ( `make-plural` on npm ), or grab an old locale file from our repo history. Those may not be up to date though.

**Comment by eekboom** [comment]
So I have added the "make-plural" dependency. Now where are the locale files?

Would be great to update the docs on the home page.

**Comment by rxaviers** [comment]
Alex or Eemeli could give you a better answer, but check this out https://github.com/eemeli/make-plural.js#dependencies. You could either download the file from https://github.com/unicode-cldr/cldr-core/ or `npm install cldr-data`.

**Comment by SlexAxton** [comment]
That'd get you files, but you don't need them. The reason they're gone is because when you pre-compile to any given language, the locale is automatically injected into the output.

The reason we have not released the current version in master is because there are no docs. Please feel free to use the current released version, which works in the way that you expect. But also feel free to try to use the version in master, since that's where things are headed, though admittedly slowly.

**Comment by eekboom** [comment]
Oops, sorry. I didn't really notice that I had a pre-release version.
I was in a hurry and just copy/pasted the version string from your package.json into mine.
